name: Auto Rename Files

on:
  push:
    paths:
      - 'input/**'
  pull_request:
    types: [closed]
    paths:
      - 'input/**'
  workflow_dispatch:

jobs:
  process-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Process and rename files
      run: |
        node << 'EOF'
        const fs = require('fs');
        const path = require('path');
        
        console.log('=== ОБРАБОТКА ФАЙЛОВ ИЗ ПАПКИ INPUT ===');
        
        // Получаем файлы из input
        const inputFiles = fs.readdirSync('input')
          .filter(f => f !== '.gitkeep' && f !== '.gitignore');
        console.log('📥 Файлы в input:', inputFiles);
        
        const jsonFiles = inputFiles.filter(f => f.endsWith('.json'));
        console.log('📄 JSON файлы для обработки:', jsonFiles);
        
        if (jsonFiles.length === 0) {
          console.log('✅ Нет новых JSON файлов для обработки');
          process.exit(0);
        }
        
        // Получаем существующие файлы в data
        let dataFiles = [];
        try {
          dataFiles = fs.readdirSync('data');
        } catch (error) {
          console.log('📁 Папка data пуста');
        }
        
        // Находим максимальный номер
        let maxNum = 0;
        dataFiles.forEach(file => {
          const match = file.match(/^graph_(\d+)\.json$/);
          if (match) {
            const num = parseInt(match[1]);
            if (num > maxNum) maxNum = num;
          }
        });
        
        console.log('🔢 Максимальный найденный номер:', maxNum);
        
        // Обрабатываем файлы
        jsonFiles.forEach(file => {
          try {
            const inputPath = path.join('input', file);
            
            // Проверяем JSON
            const content = fs.readFileSync(inputPath, 'utf8');
            JSON.parse(content);
            
            // Находим свободное имя
            maxNum++;
            const newName = `graph_${maxNum}.json`;
            const outputPath = path.join('data', newName);
            
            // Перемещаем файл
            fs.renameSync(inputPath, outputPath);
            console.log(`✅ Перемещен: ${file} -> ${newName}`);
            
          } catch (error) {
            console.log(`❌ Ошибка: ${file} - ${error.message}`);
          }
        });
        
        // Очищаем input от оставшихся файлов
        const remainingFiles = fs.readdirSync('input')
          .filter(f => f !== '.gitkeep' && f !== '.gitignore');
          
        if (remainingFiles.length > 0) {
          console.log('🗑️ Очищаем input от оставшихся файлов:', remainingFiles);
          remainingFiles.forEach(file => {
            fs.unlinkSync(path.join('input', file));
          });
        }
        
        console.log('🎉 Обработка завершена!');
        EOF
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto-process: обработка файлов из input" || echo "Нет изменений для коммита"
        git push
